# This workflow will build a Golang project using GoReleaser
# For more information see: https://github.com/goreleaser/goreleaser-action
---
name: goreleaser

on:
  workflow_call:
    secrets:
      github-token:
        description: The GitHub token to be used to publish the release
        required: false

    inputs:
      goreleaser-args:
        description: The arguments to be passed to the goreleaser command
        required: true
        type: string

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: ${{ inputs.goreleaser-args }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dnsmasq-manager-${{ github.sha }}
          path: ./dist/*